### ISSUE TITLE
Containerized TC runner uses localhost rather than AMQ hostname

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/IVCT_Framework#129]
Containerized TC runner uses ``localhost`` to connect to Active MQ. Should use proper hostname.

Stackstrace:

````
LRC: Version: pitch/lrc:5.3.2.1-alpine-v0.1
LRC: Perform initialization settings: /root/lrc/init1.sh
LRC: Set PITCH_CRCHOST=crc
LRC: Set PITCH_CRCPORT=8989
LRC: PITCH_CRCADDRESS=
LRC: PITCH_CRCHOST=crc
LRC: PITCH_CRCPORT=8989
LRC: PITCH_BOOSTHOST=
LRC: PITCH_BOOSTPORT=
LRC: Set LRC_MASTERADDRESS=crc:8989
LRC: Initialization settings performed
LRC: Wait for master at crc:8989
LRC: Wait for master at crc:8989
LRC: Wait for master at crc:8989
LRC: Wait for master at crc:8989
LRC: Wait for master at crc:8989
LRC: Master crc:8989 is up
LRC: Sleep period: 10
LRC: Set FEDERATIONNAME=TheWorld
LRC: Perform pre-start initialization settings: /root/lrc/init2.sh
LRC: Found interface eth0 for host crc with IP address 172.22.0.5
LRC: Set PITCH_CRCADDRESS=172.22.0.5:8989
LRC: Set PITCH_LRCADAPTER=eth0
LRC: PITCH_CRCADDRESS=172.22.0.5:8989
LRC: PITCH_LRCADAPTER=eth0
LRC: Pre-start initialization settings performed
LRC: Start: /root/application/start.sh
Starting the Dockerized IVCT Test Case Engine
21:30:00,575 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
21:30:00,575 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
21:30:00,575 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
21:30:00,583 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.
21:30:00,747 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@cd2dae5 - URL [jar:file:/root/application/TC.exec-1.0.1/lib/TC.exec-1.0.1.jar!/JMSTestRunner_logback.xml] is not of type file
21:30:00,886 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
21:30:00,888 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeFilter scanning period to 2 minutes
21:30:00,888 |-INFO in ReconfigureOnChangeFilter{invocationCounter=16} - Will scan for changes in [[]] every 120 seconds. 
21:30:00,888 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
21:30:00,896 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [ch.qos.logback.classic.jul.LevelChangePropagator] to the object stack
21:30:00,936 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@3a883ce7 - Propagating DEBUG level on Logger[ROOT] onto the JUL framework
21:30:00,946 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
21:30:00,946 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.net.JMSTopicAppender]
21:30:00,962 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [JMS]
21:30:01,282 |-WARN in Logger[org.apache.activemq.util.ThreadPoolUtils] - No appenders present in context [default] for logger [org.apache.activemq.util.ThreadPoolUtils].
21:30:01,290 |-ERROR in ch.qos.logback.classic.net.JMSTopicAppender[JMS] - Error while activating options for appender named [JMS]. javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
	at javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
	at 	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36)
	at 	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:360)
	at 	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:305)
	at 	at org.apache.activemq.ActiveMQConnectionFactory.createTopicConnection(ActiveMQConnectionFactory.java:279)
	at 	at ch.qos.logback.classic.net.JMSTopicAppender.start(JMSTopicAppender.java:104)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at de.fraunhofer.iosb.messaginghelpers.LogConfigurationHelper.configureLogging(LogConfigurationHelper.java:45)
	at 	at de.fraunhofer.iosb.testrunner.JMSTestRunner.main(JMSTestRunner.java:65)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at 	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at 	at java.net.Socket.connect(Socket.java:589)
	at 	at org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:501)
	at 	at org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:464)
	at 	at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
	at 	at org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:168)
	at 	at org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:50)
	at 	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58)
	at 	at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
	at 	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58)
	at 	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58)
	at 	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:340)
	at 	... 14 common frames omitted
````

**Comment by ducana** [comment]
For the 1.0.1 version of IVCT_Runtime development branch there are two ways to set the ActiveMQ hostname:
1) environment variable  set messaging.host=<hostname>
2) in the IVCT_Runtime/IVCT.properties file, the property   messaging.host=<hostname>   has to be set to the hostname/IP address of the host where ActiveMQ is running.
This makes the environment variable ACTIVEMQ_HOST obsolete for IVCT.

**Comment by bergtwvd** [comment]
I like to use env settings rather than configuration files with property settings, especially data such as host names and port numbers. There will change per deployment and in a docker environment this information is generated on the fly.

**Comment by bergtwvd** [comment]
I have pulled the latest images the issue is still there. See trace snippet below.
Although harmless here, the Runner should connect to the AMQ properly.

Are the following environment settings honored?
````
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
 ````

Stack trace for reference:

````
tc-runner_1                     | 09:40:15,969 |-ERROR in ch.qos.logback.classic.net.JMSTopicAppender[JMS] - Error while activating options for appender named [JMS]. javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
tc-runner_1                     |       at javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused (Connection refused)
tc-runner_1                     |       at      at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36)
tc-runner_1                     |       at      at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:360)
tc-runner_1                     |       at      at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:305)
tc-runner_1                     |       at      at org.apache.activemq.ActiveMQConnectionFactory.createTopicConnection(ActiveMQConnectionFactory.java:279)
tc-runner_1                     |       at      at ch.qos.logback.classic.net.JMSTopicAppender.start(JMSTopicAppender.java:104)
tc-runner_1                     |       at      at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
tc-runner_1                     |       at      at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
tc-runner_1                     |       at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
tc-runner_1                     |       at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
tc-runner_1                     |       at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
tc-runner_1                     |       at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
tc-runner_1                     |       at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
tc-runner_1                     |       at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
tc-runner_1                     |       at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
tc-runner_1                     |       at      at de.fraunhofer.iosb.messaginghelpers.LogConfigurationHelper.configureLogging(LogConfigurationHelper.java:45)
tc-runner_1                     |       at      at de.fraunhofer.iosb.testrunner.JMSTestRunner.main(JMSTestRunner.java:65)
tc-runner_1                     | Caused by: java.net.ConnectException: Connection refused (Connection refused)
tc-runner_1                     |       at      at java.net.PlainSocketImpl.socketConnect(Native Method)
tc-runner_1                     |       at      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
tc-runner_1                     |       at      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
tc-runner_1                     |       at      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
tc-runner_1                     |       at      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
tc-runner_1                     |       at      at java.net.Socket.connect(Socket.java:589)
tc-runner_1                     |       at      at org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:501)
tc-runner_1                     |       at      at org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:464)
tc-runner_1                     |       at      at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
tc-runner_1                     |       at      at org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:168)
tc-runner_1                     |       at      at org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:50)
tc-runner_1                     |       at      at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58)
tc-runner_1                     |       at      at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
tc-runner_1                     |       at      at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58)
tc-runner_1                     |       at      at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58)
tc-runner_1                     |       at      at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:340)
tc-runner_1                     |       at      ... 14 common frames omitted
tc-runner_1                     | 09:40:15,969 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
tc-runner_1                     | 09:40:15,971 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
tc-runner_1                     | 09:40:16,074 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
t
...
````

**Comment by bergtwvd** [comment]
Will check once Pieter is back from vacation in 2,5 weeks.

**Comment by PHameete** [comment]
This should use the JMSTestRunner. The Docker image contains the TC.exec project distribution, which has the JMSRunner running in its main function.

The error log shows not the ACTIVEMQ host used by the JMSTestRunner, but by the logback. This is a different issue.

**Comment by bergtwvd** [comment]
I still see the same stacktrace in the development-latest container images.

**Comment by bergtwvd** [comment]
I ran with the latest container versions, and the trace still shows up.

**Comment by ducana** [comment]
There seems to be two situations where this could occur: environment variable messaging.host is explictly set to localhost or messaging.host is not set (it will default to localhost).
Please check the value of messaging.host.
The environment variables ACTIVEMQ_HOST and ACTIVEMQ_PORT are no longer used.

**Comment by bergtwvd** [comment]
This is the same issue as https://github.com/MSG134/IVCT_Framework/issues/148. Suggest to proceed with that one and close this.
