### ISSUE TITLE
Encoding tests against VRF gives error in runner

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/IVCT_Framework#142]
When the encoding test is started, the following message appears in the TC Runner log output.

````
tc-runner_1                     | 2018-09-26 08:06:09,175 : JMSTestRunner:onMessageConsumer:run: de.fraunhofer.iosb.tc_encodingrulestester.TC0001
tc-runner_1                     | 2018-09-26 08:06:09,183 : JMSTestRunner:onMessageConsumer:run: tsRunFolder is /root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1/bin
tc-runner_1                     | 2018-09-26 08:06:09,184 : JMSTestRunner:onMessageConsumer:run: TC DIR is /root/application
tc-runner_1                     | 2018-09-26 08:06:09,185 : JMSTestRunner:onMessageConsumer:run: The test case class is: de.fraunhofer.iosb.tc_encodingrulestester.TC0001
tc-runner_1                     | Exception in thread "Thread-3" java.lang.NullPointerException
tc-runner_1                     |       at de.fraunhofer.iosb.testrunner.JMSTestRunner$TestScheduleRunner.extendThreadClassLoader(JMSTestRunner.java:140)
tc-runner_1                     |       at de.fraunhofer.iosb.testrunner.JMSTestRunner$TestScheduleRunner.run(JMSTestRunner.java:183)
tc-runner_1                     |       at java.lang.Thread.run(Thread.java:745)
```

**Comment by ducana** [comment]
The line (JMSTestRunner.java:140) is a memory allocation of an array of urls. This is not currently checked for allocation of zero nember of urls, which may lead to this exception.
The root of the problem seems to be that no files are found/readable in the "IVCT_Runtime\TestSuites\TS_HLA_EncodingRulesTester-1.0.1\lib" folder. Is it possible to check whether the contents of this folder is accessible?

**Comment by bergtwvd** [comment]
The volume handling got changed last week (irt Kubernetes). The shipsim composition was not correct anymore. I just fixed it and committed a corrected version. Works now.
