### ISSUE TITLE
FOM merge error with MaK RTI

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/IVCT_Framework#171]
When I use the Shipsim test composition for the encoding tests using the MaK RTI (see https://github.com/MSG134/IVCT_Compositions/blob/master/Shipsim/ma-docker-compose.yml), then I get a FOM merge error.

Note that the RID settings for the MaK LRC base image are configured to be strict.

Clues?

Log:

````
tc-runner_1              | LRC: Version: vtmak/lrc:4.5-alpine-v0.4
tc-runner_1              | LRC: Copyright (C) TNO 2018 (www.tno.nl)
tc-runner_1              | LRC: No pre-wait initialization performed
tc-runner_1              | LRC: No master address provided; no wait on master
tc-runner_1              | LRC: No sleep period provided
tc-runner_1              | LRC: Set FEDERATIONNAME=TheWorld
tc-runner_1              | LRC: Perform post-wait initialization: /root/lrc/postwait.sh
tc-runner_1              | LRC: Set MAK_RTIEXECHOST=rtiexec
tc-runner_1              | LRC: Set MAK_RTIEXECPORT=4000
tc-runner_1              | LRC: Set RTI_tcpForwarderAddr to rtiexec
tc-runner_1              | LRC: Set RTI_tcpPort to 4000
tc-runner_1              | LRC: Set RTI_udpPort to 4000
tc-runner_1              | LRC: Post-wait Initialization completed
tc-runner_1              | LRC: Exec: /root/application/start.sh
tc-runner_1              | Starting the Dockerized IVCT Test Case Engine
tc-runner_1              | 10:27:35.183 [main] DEBUG nato.ivct.commander.Factory - /root/conf/ exists
tc-runner_1              | 10:27:35.191 [main] DEBUG nato.ivct.commander.Factory - /root/conf/ is directory
tc-runner_1              | 10:27:35.192 [main] INFO  nato.ivct.commander.Factory - Properties file loaded
tc-runner_1              | 10:27:35.194 [main] INFO  nato.ivct.commander.Factory - Environment Variable ACTIVEMQ_HOST = activemq found
tc-runner_1              | 10:27:35.198 [main] INFO  nato.ivct.commander.Factory - Properties used: {ACTIVEMQ_HOST=activemq, messaging.user=admin, RTI_ID=pRTI, IVCT_TS_HOME_ID=/root/conf/TestSuites, jmstestrunner.queue=commands, messaging.password=admin, IVCT_SUT_HOME_ID=/root/conf/IVCTsut, messaging.host=activemq, IVCT_BADGE_HOME_ID=/root/conf/Badges, messaging.port=61616, ivctcommander.queue=commands}
tc-runner_1              | 10:27:35.283 [main] INFO  d.f.i.m.PropertyBasedClientSetup - initConnection: connect to activemq please wait...
tc-runner_1              | 10:27:35.625 [main] DEBUG o.a.activemq.util.ThreadPoolUtils - Shutdown of ExecutorService: java.util.concurrent.ThreadPoolExecutor@6bf256fa[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] is shutdown: true and terminated: true took: 0.001 seconds.
tc-runner_1              | 10:27:35.626 [main] DEBUG o.a.a.transport.tcp.TcpTransport - Stopping transport tcp://activemq:61616
tc-runner_1              | 10:27:35.629 [main] DEBUG o.a.a.thread.TaskRunnerFactory - Initialized TaskRunnerFactory[ActiveMQ Task] using ExecutorService: java.util.concurrent.ThreadPoolExecutor@668bc3d5[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
tc-runner_1              | 10:27:35.631 [ActiveMQ Task-1] DEBUG o.a.a.transport.tcp.TcpTransport - Closed socket Socket[unconnected]
tc-runner_1              | 10:27:35.632 [main] DEBUG o.a.activemq.util.ThreadPoolUtils - Forcing shutdown of ExecutorService: java.util.concurrent.ThreadPoolExecutor@668bc3d5[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
tc-runner_1              | 10:27:40.636 [main] DEBUG o.a.a.transport.WireFormatNegotiator - Sending: WireFormatInfo { version=11, properties={TcpNoDelayEnabled=true, SizePrefixDisabled=false, CacheSize=1024, StackTraceEnabled=true, CacheEnabled=true, TightEncodingEnabled=true, MaxFrameSize=9223372036854775807, Host=activemq, MaxInactivityDuration=30000, MaxInactivityDurationInitalDelay=10000}, magic=[A,c,t,i,v,e,M,Q]}
tc-runner_1              | 10:27:40.930 [ActiveMQ Transport: tcp://activemq/172.26.0.2:61616@34571] DEBUG o.a.a.transport.InactivityMonitor - Using min of local: WireFormatInfo { version=11, properties={TcpNoDelayEnabled=true, SizePrefixDisabled=false, CacheSize=1024, StackTraceEnabled=true, CacheEnabled=true, TightEncodingEnabled=true, MaxFrameSize=9223372036854775807, Host=activemq, MaxInactivityDuration=30000, MaxInactivityDurationInitalDelay=10000}, magic=[A,c,t,i,v,e,M,Q]} and remote: WireFormatInfo { version=12, properties={TcpNoDelayEnabled=true, SizePrefixDisabled=false, CacheSize=1024, ProviderName=ActiveMQ, StackTraceEnabled=true, PlatformDetails=JVM: 1.8.0_131, 25.131-b11, Oracle Corporation, OS: Linux, 3.13.0-123-generic, amd64, CacheEnabled=true, TightEncodingEnabled=true, MaxFrameSize=104857600, MaxInactivityDuration=30000, MaxInactivityDurationInitalDelay=10000, ProviderVersion=5.14.5}, magic=[A,c,t,i,v,e,M,Q]}
tc-runner_1              | 10:27:40.949 [ActiveMQ Transport: tcp://activemq/172.26.0.2:61616@34571] DEBUG o.a.a.transport.WireFormatNegotiator - Received WireFormat: WireFormatInfo { version=12, properties={TcpNoDelayEnabled=true, SizePrefixDisabled=false, CacheSize=1024, ProviderName=ActiveMQ, StackTraceEnabled=true, PlatformDetails=JVM: 1.8.0_131, 25.131-b11, Oracle Corporation, OS: Linux, 3.13.0-123-generic, amd64, CacheEnabled=true, TightEncodingEnabled=true, MaxFrameSize=104857600, MaxInactivityDuration=30000, MaxInactivityDurationInitalDelay=10000, ProviderVersion=5.14.5}, magic=[A,c,t,i,v,e,M,Q]}
tc-runner_1              | 10:27:40.949 [ActiveMQ Transport: tcp://activemq/172.26.0.2:61616@34571] DEBUG o.a.a.transport.WireFormatNegotiator - tcp://activemq/172.26.0.2:61616@34571 before negotiation: OpenWireFormat{version=11, cacheEnabled=false, stackTraceEnabled=false, tightEncodingEnabled=false, sizePrefixDisabled=false, maxFrameSize=9223372036854775807}
tc-runner_1              | 10:27:40.950 [ActiveMQ Transport: tcp://activemq/172.26.0.2:61616@34571] DEBUG o.a.a.transport.WireFormatNegotiator - tcp://activemq/172.26.0.2:61616@34571 after negotiation: OpenWireFormat{version=11, cacheEnabled=true, stackTraceEnabled=true, tightEncodingEnabled=true, sizePrefixDisabled=false, maxFrameSize=104857600}
tc-runner_1              | 10:27:41.248 [main] INFO  d.f.i.m.PropertyBasedClientSetup - initConnection: connect to activemq OK
tc-runner_1              | 10:27:34,971 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
tc-runner_1              | 10:27:34,971 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
tc-runner_1              | 10:27:34,971 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
tc-runner_1              | 10:27:34,984 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.
tc-runner_1              | 10:27:41,972 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
tc-runner_1              | 10:27:41,977 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeFilter scanning period to 2 minutes
tc-runner_1              | 10:27:41,978 |-INFO in ReconfigureOnChangeFilter{invocationCounter=15} - Will scan for changes in [[/root/application/TC.exec-1.0.1/lib/JMSTestRunner_logback.xml]] every 120 seconds.
tc-runner_1              | 10:27:41,978 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
tc-runner_1              | 10:27:41,985 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [ch.qos.logback.classic.jul.LevelChangePropagator] to the object stack
tc-runner_1              | 10:27:42,063 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@6f195bc3 - Propagating DEBUG level on Logger[ROOT] onto the JUL framework
tc-runner_1              | 10:27:42,085 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
tc-runner_1              | 10:27:42,085 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.net.JMSTopicAppender]
tc-runner_1              | 10:27:42,087 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [JMS]
tc-runner_1              | 10:27:42,211 |-WARN in Logger[org.apache.activemq.transport.WireFormatNegotiator] - No appenders present in context [default] for logger [org.apache.activemq.transport.WireFormatNegotiator].
tc-runner_1              | 10:27:42,301 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
tc-runner_1              | 10:27:42,304 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
tc-runner_1              | 10:27:42,393 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
tc-runner_1              | 10:27:42,397 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern ./logs/LogSinkTest.%d{yyyy-MM-dd}.%i.log for the active file
tc-runner_1              | 10:27:42,399 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@51e2adc7 - The date pattern is 'yyyy-MM-dd' from file name pattern './logs/LogSinkTest.%d{yyyy-MM-dd}.%i.log'.
tc-runner_1              | 10:27:42,399 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@51e2adc7 - Roll-over at midnight.
tc-runner_1              | 10:27:42,410 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@51e2adc7 - Setting initial period to Fri Dec 14 10:27:42 GMT 2018
tc-runner_1              | 10:27:42,412 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
tc-runner_1              | 10:27:42,432 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: ./logs/LogSinkTest.log
tc-runner_1              | 10:27:42,432 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [./logs/LogSinkTest.log]
tc-runner_1              | 10:27:42,433 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
tc-runner_1              | 10:27:42,433 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
tc-runner_1              | 10:27:42,450 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
tc-runner_1              | 10:27:42,452 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
tc-runner_1              | 10:27:42,452 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@6f195bc3 - Propagating INFO level on Logger[ROOT] onto the JUL framework
tc-runner_1              | 10:27:42,452 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
tc-runner_1              | 10:27:42,452 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
tc-runner_1              | 10:27:42,452 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [JMS] to Logger[ROOT]
tc-runner_1              | 10:27:42,458 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [de.fraunhofer.iosb] to INFO
tc-runner_1              | 10:27:42,458 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@6f195bc3 - Propagating INFO level on Logger[de.fraunhofer.iosb] onto the JUL framework
tc-runner_1              | 10:27:42,458 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
tc-runner_1              | 10:27:42,458 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1a8a8f7c - Registering current configuration as safe fallback point
tc-runner_1              |
tc-runner_1              | 2018-12-14 10:28:34,632 : JMSTestRunner:onMessageConsumer:run: de.fraunhofer.iosb.tc_encodingrulestester.TC0001
tc-runner_1              | 2018-12-14 10:28:34,664 : JMSTestRunner:onMessageConsumer:run: tsRunFolder is /root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1/bin
tc-runner_1              | 2018-12-14 10:28:34,668 : JMSTestRunner:onMessageConsumer:run: setCurrentDirectory true
tc-runner_1              | 2018-12-14 10:28:34,670 : JMSTestRunner:onMessageConsumer:run: TC DIR is /root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1/bin
tc-runner_1              | 2018-12-14 10:28:34,672 : JMSTestRunner:onMessageConsumer:run: The test case class is: de.fraunhofer.iosb.tc_encodingrulestester.TC0001
tc-runner_1              | 2018-12-14 10:28:34,684 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: Test Case Started
tc-runner_1              | 2018-12-14 10:28:34,686 de.fraunhofer.iosb.tc_encodingrulestester.TC0001:
tc-runner_1              | TEST CASE PARAMETERS -------------------------------------- BEGIN
tc-runner_1              | {"somFiles":[{"fileName":"\/root\/conf\/IVCTsut\/vrf\/TS_HLA_EncodingRulesTester-2017\/BasicSimpleTypes.xml"},{"fileName":"\/root\/conf\/IVCTsut\/vrf\/TS_HLA_EncodingRulesTester-2017\/RPR_FOM_v2.0_1516-2010.xml"}],"fomFiles":[{"fileName":"\/root\/conf\/IVCTsut\/vrf\/TS_HLA_EncodingRulesTester-2017\/RPR_FOM_v2.0_1516-2010.xml"},{"fileName":"\/root\/conf\/IVCTsut\/vrf\/TS_HLA_EncodingRulesTester-2017\/BasicSimpleTypes.xml"}],"rtiHostName":"crc","federationName":"TheWorld","sleepTestTimeWaitSeconds":"60","rtiPort":"8989","sutFederateName":"VRF\/UG"}
tc-runner_1              | TEST CASE PARAMETERS -------------------------------------- END
tc-runner_1              |
tc-runner_1              | Using MAK Technologies' RTI version 4.5d HLA 1516-2010 for GNU C++ version 4.8.5 20150623 (Red Hat 4.8.5-11).
tc-runner_1              | 2018-12-14 10:28:34,785 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: DISPLAY SOME HELPER VERSION NUMBER TO CONFIRM VERSION USED: 2018-12-12
tc-runner_1              | 2018-12-14 10:28:34,796 de.fraunhofer.iosb.tc_encodingrulestester.TC0001:
tc-runner_1              | ---------------------------------------------------------------------
tc-runner_1              | TEST PURPOSE: Test if a federate correctly encodes the attribute and parameter data
tc-runner_1              | TEST PURPOSE: fields
tc-runner_1              | TEST PURPOSE: Use the SOM files to discover which classes the federate publishes and
tc-runner_1              | TEST PURPOSE: subscribe to these. For each attribute or parameter data received, use
tc-runner_1              | TEST PURPOSE: the OMT encoding rules to test if the buffer is consistent to the OMT
tc-runner_1              | TEST PURPOSE: encoding rules: length, padding and enumerator values.
tc-runner_1              | TEST PURPOSE: This does not imply correctness of the data item values
tc-runner_1              | ---------------------------------------------------------------------
tc-runner_1              |
tc-runner_1              | 2018-12-14 10:28:34,806 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: TEST CASE PREAMBLE
tc-runner_1              | 2018-12-14 10:28:34,809 de.fraunhofer.iosb.tc_encodingrulestester.TC0001:
tc-runner_1              | ---------------------------------------------------------------------
tc-runner_1              | OPERATOR INSTRUCTIONS: Start the test federate before starting the test case with the same
tc-runner_1              | OPERATOR INSTRUCTIONS: federate name as in the TcParam.json file
tc-runner_1              | OPERATOR INSTRUCTIONS: The federate should run for the full duration of all the encoding
tc-runner_1              | OPERATOR INSTRUCTIONS: rules test
tc-runner_1              | ---------------------------------------------------------------------
tc-runner_1              |
tc-runner_1              | Loading Config File: /etc/makrti/rid.mtl
tc-runner_1              | 2018-12-14 10:28:35,495 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: createFederationExecution exception=FederationExecutionAlreadyExists
tc-runner_1              | 2018-12-14 10:28:35,498 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: initiateRti: FederationExecutionAlreadyExists (ignored)
tc-runner_1              | rtiexec and joining federate have mismatched CRC values for Fed File
tc-runner_1              | RPR_FOM_v2.0_1516-2010.xml
tc-runner_1              | The RTI could not merge the .fdd/.xml (or .fed) file during join.
tc-runner_1              | This error occurred during Join in the function DtRtiExecFederateMgr::initializeFOM.
tc-runner_1              | InconsistentFDD  Error merging FOM BasicSimpleTypes.xml. Failed merging user defined tags.
tc-runner_1              | 2018-12-14 10:28:37,767 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: joinFederationExecution exception=RTIinternalError  Join failed to process FDD
tc-runner_1              | InconsistentFDD  Error merging FOM BasicSimpleTypes.xml. Failed merging user defined tags.
tc-runner_1              | 2018-12-14 10:28:37,778 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: initiateRti:
tc-runner_1              | hla.rti1516e.exceptions.RTIinternalError: RTIinternalError  Join failed to process FDD
tc-runner_1              | InconsistentFDD  Error merging FOM BasicSimpleTypes.xml. Failed merging user defined tags.
tc-runner_1              |      at com.mak.makrti1516e.jni.DtJniRTIambassador.joinFederationExecution2(Native Method) ~[hla.jar:na]
tc-runner_1              |      at com.mak.makrti1516e.DtRTIambassador.joinFederationExecution(DtRTIambassador.java:485) ~[hla.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.IVCT_RTIambassador.joinFederationExecution(IVCT_RTIambassador.java:382) ~[TC.lib-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.IVCT_BaseModel.initiateRti(IVCT_BaseModel.java:110) ~[TC.lib-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.tc_encodingrulestester.TC0001.preambleAction(TC0001.java:99) [TS_HLA_EncodingRulesTester-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:137) [TC.lib-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.testrunner.TestRunner.executeTests(TestRunner.java:78) [TC.exec-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.testrunner.JMSTestRunner$TestScheduleRunner.run(JMSTestRunner.java:186) [TC.exec-1.0.1.jar:na]
tc-runner_1              |      at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
tc-runner_1              | 2018-12-14 10:28:37,941 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleObjectClass.decode: objects
tc-runner_1              | 2018-12-14 10:28:37,944 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: getObjectClassHandle exception=FederateNotExecutionMember  Federate not joined when calling getObjectClassHandle
tc-runner_1              | 2018-12-14 10:28:37,946 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleObjectClass.decodeObjectClass: hla.rti1516e.exceptions.FederateNotExecutionMember: FederateNotExecutionMember  Federate not joined when calling getObjectClassHandle
tc-runner_1              | 2018-12-14 10:28:37,947 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: getInteractionClassHandle exception=FederateNotExecutionMember  Federate not joined when calling getInteractionClassHandle
tc-runner_1              | 2018-12-14 10:28:37,957 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleInteractionClass.decodeInteractionClass: hla.rti1516e.exceptions.FederateNotExecutionMember: FederateNotExecutionMember  Federate not joined when calling getInteractionClassHandle
tc-runner_1              | 2018-12-14 10:28:37,959 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: getInteractionClassHandle exception=FederateNotExecutionMember  Federate not joined when calling getInteractionClassHandle
tc-runner_1              | 2018-12-14 10:28:37,965 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: getInteractionClassHandle exception=FederateNotExecutionMember  Federate not joined when calling getInteractionClassHandle
tc-runner_1              | 2018-12-14 10:28:37,969 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleInteractionClass.decodeInteractionClass: hla.rti1516e.exceptions.FederateNotExecutionMember: FederateNotExecutionMember  Federate not joined when calling getInteractionClassHandle
tc-runner_1              | 2018-12-14 10:28:37,971 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleInteractionClass.decodeParameter: java.lang.NullPointerException
tc-runner_1              | 2018-12-14 10:28:38,006 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleObjectClass.decode: objects
tc-runner_1              | 2018-12-14 10:28:38,014 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: getObjectClassHandle exception=FederateNotExecutionMember  Federate not joined when calling getObjectClassHandle
tc-runner_1              | 2018-12-14 10:28:38,017 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleObjectClass.decodeObjectClass: hla.rti1516e.exceptions.FederateNotExecutionMember: FederateNotExecutionMember  Federate not joined when calling getObjectClassHandle
tc-runner_1              | 2018-12-14 10:28:38,026 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: getInteractionClassHandle exception=FederateNotExecutionMember  Federate not joined when calling getInteractionClassHandle
tc-runner_1              | 2018-12-14 10:28:38,029 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleInteractionClass.decodeInteractionClass: hla.rti1516e.exceptions.FederateNotExecutionMember: FederateNotExecutionMember  Federate not joined when calling getInteractionClassHandle
tc-runner_1              | 2018-12-14 10:28:38,037 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleDataTypes.decodeBasicData: EQUAL DATA TYPE: HLAinteger16BE IGNORED
tc-runner_1              | 2018-12-14 10:28:38,040 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleDataTypes.decodeBasicData: EQUAL DATA TYPE: HLAinteger32BE IGNORED
tc-runner_1              | 2018-12-14 10:28:38,041 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleDataTypes.decodeBasicData: EQUAL DATA TYPE: HLAfloat32BE IGNORED
tc-runner_1              | 2018-12-14 10:28:38,047 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleDataTypes.decodeBasicData: EQUAL DATA TYPE: HLAfloat64BE IGNORED
tc-runner_1              | 2018-12-14 10:28:38,049 de.fraunhofer.iosb.tc_encodingrulestester.TC0001: HandleDataTypes.decodeBasicData: EQUAL DATA TYPE: HLAoctet IGNORED
tc-runner_1              | Exception in thread "Thread-3" java.lang.NullPointerException
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.IVCT_RTIambassador.getInteractionClassName(IVCT_RTIambassador.java:1846)
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib_encodingrulestester.EncodingRulesTesterBaseModel.init(EncodingRulesTesterBaseModel.java:320)
tc-runner_1              |      at de.fraunhofer.iosb.tc_encodingrulestester.TC0001.preambleAction(TC0001.java:102)
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:137)
tc-runner_1              |      at de.fraunhofer.iosb.testrunner.TestRunner.executeTests(TestRunner.java:78)
tc-runner_1              |      at de.fraunhofer.iosb.testrunner.JMSTestRunner$TestScheduleRunner.run(JMSTestRunner.java:186)
tc-runner_1              |      at java.lang.Thread.run(Thread.java:748)
````

**Comment by ducana** [comment]
It seems that there is a conflict in the files BasicSimpleTypes.xml and RPR_FOM_v2.0_1516-2010.xml. The RTI says: Failed merging user defined tags. Normally the FOM/SOM files can only be merged when the definitions are identical for the same type in all files.

**Comment by bergtwvd** [comment]
That's right, but I do not see any issues with the files. I need to reproduce this outside the IVCT; probably beginning of next year.

The reason why this worked in the last with the MaK LRC image is that I used relaxed RTI compliance settings. In the latest MaK LRC image the settings are for strict compliance.

**Comment by bergtwvd** [comment]
The feedback from MaK is:

> The problem with the merge is the user defined tags. The specification indicates that this table shall be identical in all FOM modules if present. The BasicSimpleTypes.xml file includes the table as empty which is not the same as being omitted and this conflicts with the user defined tags included in RPR_FOM_v2.0_1516-2010.xml.
> 
> "The tables for time representation, switches, and user defined tags shall be provided in at least one
> FOM or SOM. The tables shall be identical to the corresponding tables in the FOM/SOM modules."


So the ``<tags></tags>`` needs to be removed from ``BasicSimpleTypes.xml``.

**Comment by bergtwvd** [comment]
P.s. what tool was used to create the ``BasicSimpleTypes.xml`` file ?

**Comment by ducana** [comment]
We don't use any tools for editing the FOM/SOM files. The file was simply created by an editor without any consistency checks. The <tags></tags> section can be deleted from the BasicSimpleTypes.xml file.

**Comment by bergtwvd** [comment]
Fixed by removing the tags section from the FOM.
