### ISSUE TITLE
Editing of TC Parms

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/IVCT_Framework#190]
I edits TC parm, but the Encoding TS does not seem to pick them up.

From TC Execution Log:
````
2019-04-04 14:38:23,042 WARN [d.f.iosb.testrunner.JMSTestRunner] [AbstractTestCase.java:100] de.fraunhofer.iosb.tc_encodingrulestester.TC0002: Test Case Started
2019-04-04 14:38:23,043 INFO [d.f.iosb.testrunner.JMSTestRunner] [AbstractTestCase.java:110] de.fraunhofer.iosb.tc_encodingrulestester.TC0002: 
TEST CASE PARAMETERS -------------------------------------- BEGIN
{"somFiles":[{"fileName":"\/root\/conf\/IVCTsut\/vrf\/EncodingRulesTesterRPR\/BasicSimpleTypes.xml"},{"fileName":"\/root\/conf\/IVCTsut\/vrf\/EncodingRulesTesterRPR\/RPR_FOM_v2.0_1516-2010.xml"}],"fomFiles":[{"fileName":"\/root\/conf\/IVCTsut\/vrf\/EncodingRulesTesterRPR\/RPR_FOM_v2.0_1516-2010.xml"},{"fileName":"\/root\/conf\/IVCTsut\/vrf\/EncodingRulesTesterRPR\/BasicSimpleTypes.xml"}],"rtiHostName":"CRC.NETNBOOSTER@booster.booster1","federationName":"TheWorld","sleepTestTimeWaitSeconds":"60","rtiPort":"8688","sutFederateName":"VIEWER1"}
TEST CASE PARAMETERS -------------------------------------- END
````

From application console:
````
LRC: Version: pitch/lrc:5.4.0.0-alpine-v0.4

LRC: Copyright (C) TNO 2018 (www.tno.nl)

LRC: Perform pre-wait initialization: /root/lrc/prewait.sh

LRC: Pre-wait Initialization completed

LRC: No master address provided; no wait on master

LRC: No sleep period provided

LRC: Set FEDERATIONNAME=TheWorld

LRC: Perform post-wait initialization: /root/lrc/postwait.sh

LRC: PITCH_CRCADDRESS=crc.crc:8989

LRC: Post-wait Initialization completed

LRC: Exec: /root/application/start.sh

Starting the Dockerized IVCT Test Case Engine

14:15:14.970 [main] DEBUG nato.ivct.commander.Factory - /root/conf/ exists

14:15:14.988 [main] DEBUG nato.ivct.commander.Factory - /root/conf/ is directory

14:15:14.989 [main] INFO nato.ivct.commander.Factory - Properties file loaded

14:15:14.991 [main] INFO nato.ivct.commander.Factory - Properties used: {messaging.user=admin, RTI_ID=pRTI, IVCT_TS_HOME_ID=/root/conf/TestSuites, jmstestrunner.queue=commands, messaging.password=admin, IVCT_SUT_HOME_ID=/root/conf/IVCTsut, messaging.host=activemq, IVCT_BADGE_HOME_ID=/root/conf/Badges, messaging.port=61616, ivctcommander.queue=commands}

14:15:15.100 [main] INFO d.f.i.m.PropertyBasedClientSetup - initConnection: connect to activemq please wait...

14:15:15.435 [main] DEBUG o.a.activemq.util.ThreadPoolUtils - Shutdown of ExecutorService: java.util.concurrent.ThreadPoolExecutor@26ba2a48[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] is shutdown: true and terminated: true took: 0.001 seconds.

14:15:15.436 [main] DEBUG o.a.a.transport.tcp.TcpTransport - Stopping transport tcp://localhost:61616

14:15:15.438 [main] DEBUG o.a.a.thread.TaskRunnerFactory - Initialized TaskRunnerFactory[ActiveMQ Task] using ExecutorService: java.util.concurrent.ThreadPoolExecutor@2c6a3f77[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]

14:15:15.440 [ActiveMQ Task-1] DEBUG o.a.a.transport.tcp.TcpTransport - Closed socket Socket[unconnected]

14:15:15.440 [main] DEBUG o.a.activemq.util.ThreadPoolUtils - Forcing shutdown of ExecutorService: java.util.concurrent.ThreadPoolExecutor@2c6a3f77[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]

14:15:20.460 [main] DEBUG o.a.a.transport.WireFormatNegotiator - Sending: WireFormatInfo { version=11, properties={TcpNoDelayEnabled=true, SizePrefixDisabled=false, CacheSize=1024, StackTraceEnabled=true, CacheEnabled=true, TightEncodingEnabled=true, MaxFrameSize=9223372036854775807, Host=localhost, MaxInactivityDuration=30000, MaxInactivityDurationInitalDelay=10000}, magic=[A,c,t,i,v,e,M,Q]}

14:15:20.534 [ActiveMQ Transport: tcp://localhost/127.0.0.1:61616@55664] DEBUG o.a.a.transport.InactivityMonitor - Using min of local: WireFormatInfo { version=11, properties={TcpNoDelayEnabled=true, SizePrefixDisabled=false, CacheSize=1024, StackTraceEnabled=true, CacheEnabled=true, TightEncodingEnabled=true, MaxFrameSize=9223372036854775807, Host=localhost, MaxInactivityDuration=30000, MaxInactivityDurationInitalDelay=10000}, magic=[A,c,t,i,v,e,M,Q]} and remote: WireFormatInfo { version=12, properties={TcpNoDelayEnabled=true, SizePrefixDisabled=false, CacheSize=1024, ProviderName=ActiveMQ, StackTraceEnabled=true, PlatformDetails=JVM: 1.8.0_131, 25.131-b11, Oracle Corporation, OS: Linux, 4.4.0-53-generic, amd64, CacheEnabled=true, TightEncodingEnabled=true, MaxFrameSize=104857600, MaxInactivityDuration=30000, MaxInactivityDurationInitalDelay=10000, ProviderVersion=5.14.5}, magic=[A,c,t,i,v,e,M,Q]}

14:15:20.537 [ActiveMQ Transport: tcp://localhost/127.0.0.1:61616@55664] DEBUG o.a.a.transport.WireFormatNegotiator - Received WireFormat: WireFormatInfo { version=12, properties={TcpNoDelayEnabled=true, SizePrefixDisabled=false, CacheSize=1024, ProviderName=ActiveMQ, StackTraceEnabled=true, PlatformDetails=JVM: 1.8.0_131, 25.131-b11, Oracle Corporation, OS: Linux, 4.4.0-53-generic, amd64, CacheEnabled=true, TightEncodingEnabled=true, MaxFrameSize=104857600, MaxInactivityDuration=30000, MaxInactivityDurationInitalDelay=10000, ProviderVersion=5.14.5}, magic=[A,c,t,i,v,e,M,Q]}

14:15:20.537 [ActiveMQ Transport: tcp://localhost/127.0.0.1:61616@55664] DEBUG o.a.a.transport.WireFormatNegotiator - tcp://localhost/127.0.0.1:61616@55664 before negotiation: OpenWireFormat{version=11, cacheEnabled=false, stackTraceEnabled=false, tightEncodingEnabled=false, sizePrefixDisabled=false, maxFrameSize=9223372036854775807}

14:15:20.546 [ActiveMQ Transport: tcp://localhost/127.0.0.1:61616@55664] DEBUG o.a.a.transport.WireFormatNegotiator - tcp://localhost/127.0.0.1:61616@55664 after negotiation: OpenWireFormat{version=11, cacheEnabled=true, stackTraceEnabled=true, tightEncodingEnabled=true, sizePrefixDisabled=false, maxFrameSize=104857600}

14:15:20.595 [main] INFO d.f.i.m.PropertyBasedClientSetup - initConnection: connect to activemq OK

14:15:14,602 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]

14:15:14,602 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]

14:15:14,602 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]

14:15:14,616 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.

14:15:20,900 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set

14:15:20,912 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeFilter scanning period to 2 minutes

14:15:20,912 |-INFO in ReconfigureOnChangeFilter{invocationCounter=15} - Will scan for changes in [[/root/application/TC.exec-1.0.1/lib/JMSTestRunner_logback.xml]] every 120 seconds.

14:15:20,912 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter

14:15:20,915 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [ch.qos.logback.classic.jul.LevelChangePropagator] to the object stack

14:15:21,005 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5bb21b69 - Propagating DEBUG level on Logger[ROOT] onto the JUL framework

14:15:21,035 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener

14:15:21,035 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.net.JMSTopicAppender]

14:15:21,039 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [JMS]

14:15:21,136 |-WARN in Logger[org.apache.activemq.transport.WireFormatNegotiator] - No appenders present in context [default] for logger [org.apache.activemq.transport.WireFormatNegotiator].

14:15:21,252 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]

14:15:21,254 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]

14:15:21,348 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used

14:15:21,350 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern ./logs/LogSinkTest.%d{yyyy-MM-dd}.%i.log for the active file

14:15:21,354 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6b9651f3 - The date pattern is 'yyyy-MM-dd' from file name pattern './logs/LogSinkTest.%d{yyyy-MM-dd}.%i.log'.

14:15:21,354 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6b9651f3 - Roll-over at midnight.

14:15:21,372 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6b9651f3 - Setting initial period to Thu Apr 04 14:15:21 GMT 2019

14:15:21,375 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property

14:15:21,393 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: ./logs/LogSinkTest.log

14:15:21,393 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [./logs/LogSinkTest.log]

14:15:21,396 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]

14:15:21,396 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]

14:15:21,397 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property

14:15:21,398 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO

14:15:21,398 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5bb21b69 - Propagating INFO level on Logger[ROOT] onto the JUL framework

14:15:21,398 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]

14:15:21,398 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]

14:15:21,398 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [JMS] to Logger[ROOT]

14:15:21,398 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [de.fraunhofer.iosb] to INFO

14:15:21,398 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5bb21b69 - Propagating INFO level on Logger[de.fraunhofer.iosb] onto the JUL framework

14:15:21,399 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.

14:15:21,399 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@38bc8ab5 - Registering current configuration as safe fallback point

2019-04-04 14:38:22,952 : JMSTestRunner:onMessageConsumer:run: de.fraunhofer.iosb.tc_encodingrulestester.TC0002

2019-04-04 14:38:23,019 : JMSTestRunner:onMessageConsumer:run: tsRunFolder is /root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1/bin

2019-04-04 14:38:23,024 : JMSTestRunner:onMessageConsumer:run: setCurrentDirectory true

2019-04-04 14:38:23,028 : JMSTestRunner:onMessageConsumer:run: TC DIR is /root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1/bin

2019-04-04 14:38:23,029 : JMSTestRunner:onMessageConsumer:run: The test case class is: de.fraunhofer.iosb.tc_encodingrulestester.TC0002

2019-04-04 14:38:23,042 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: Test Case Started

2019-04-04 14:38:23,043 de.fraunhofer.iosb.tc_encodingrulestester.TC0002:

TEST CASE PARAMETERS -------------------------------------- BEGIN

{"somFiles":[{"fileName":"\/root\/conf\/IVCTsut\/vrf\/EncodingRulesTesterRPR\/BasicSimpleTypes.xml"},{"fileName":"\/root\/conf\/IVCTsut\/vrf\/EncodingRulesTesterRPR\/RPR_FOM_v2.0_1516-2010.xml"}],"fomFiles":[{"fileName":"\/root\/conf\/IVCTsut\/vrf\/EncodingRulesTesterRPR\/RPR_FOM_v2.0_1516-2010.xml"},{"fileName":"\/root\/conf\/IVCTsut\/vrf\/EncodingRulesTesterRPR\/BasicSimpleTypes.xml"}],"rtiHostName":"CRC.NETNBOOSTER@booster.booster1","federationName":"TheWorld","sleepTestTimeWaitSeconds":"60","rtiPort":"8688","sutFederateName":"VIEWER1"}

TEST CASE PARAMETERS -------------------------------------- END

2019-04-04 14:38:23,235 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: DISPLAY SOME HELPER VERSION NUMBER TO CONFIRM VERSION USED: 2019-01-04T15:00

2019-04-04 14:38:23,242 de.fraunhofer.iosb.tc_encodingrulestester.TC0002:

---------------------------------------------------------------------

TEST PURPOSE: Test if a federate correctly encodes the attribute and parameter data

TEST PURPOSE: fields

TEST PURPOSE: Use the SOM files to discover which classes the federate publishes and

TEST PURPOSE: subscribe to these. For each attribute or parameter data received, use

TEST PURPOSE: the OMT encoding rules to test if the buffer is consistent to the OMT

TEST PURPOSE: encoding rules: length, padding and enumerator values.

TEST PURPOSE: This does not imply correctness of the data item values

---------------------------------------------------------------------

2019-04-04 14:38:23,244 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: TEST CASE PREAMBLE

2019-04-04 14:38:23,246 de.fraunhofer.iosb.tc_encodingrulestester.TC0002:

---------------------------------------------------------------------

OPERATOR INSTRUCTIONS: Start the test federate before starting the test case with the same

OPERATOR INSTRUCTIONS: federate name as in the TcParam.json file

OPERATOR INSTRUCTIONS: The federate should run for the full duration of all the encoding

OPERATOR INSTRUCTIONS: rules test

---------------------------------------------------------------------

2019-04-04 14:38:28,749 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: connect exception=Failed to connect to CRC at 'crc.crc/10.43.28.31:8989'. Check address and make sure that CRC is running.

2019-04-04 14:38:28,755 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: initiateRti:

hla.rti1516e.exceptions.ConnectionFailed: Failed to connect to CRC at 'crc.crc/10.43.28.31:8989'. Check address and make sure that CRC is running.

at se.pitch.prti1516e.lrc.p.<init>(prticore_b2920:314) ~[prticore.jar:na]

at se.pitch.prti1516e.lrc.p.a(prticore_b2920:606) ~[prticore.jar:na]

at se.pitch.prti1516e.lrc.H.connect(prticore_b2920:48) ~[prticore.jar:na]

at se.pitch.prti1516e.lrc.H.connect(prticore_b2920:72) ~[prticore.jar:na]

at se.pitch.prti1516e.lrc.G.connect(prticore_b2920:100) ~[prticore.jar:na]

at se.pitch.prti1516e.lrc.J.connect(prticore_b2920:570) ~[prticore.jar:na]

at de.fraunhofer.iosb.tc_lib.IVCT_RTIambassador.connect(IVCT_RTIambassador.java:226) ~[TC.lib-1.0.1.jar:na]

at de.fraunhofer.iosb.tc_lib.IVCT_BaseModel.initiateRti(IVCT_BaseModel.java:82) ~[TC.lib-1.0.1.jar:na]

at de.fraunhofer.iosb.tc_encodingrulestester.TC0002.preambleAction(TC0002.java:100) [TS_HLA_EncodingRulesTester-1.0.1.jar:na]

at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:137) [TC.lib-1.0.1.jar:na]

at de.fraunhofer.iosb.testrunner.TestRunner.executeTests(TestRunner.java:78) [TC.exec-1.0.1.jar:na]

at de.fraunhofer.iosb.testrunner.JMSTestRunner$TestScheduleRunner.run(JMSTestRunner.java:186) [TC.exec-1.0.1.jar:na]

at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]

2019-04-04 14:38:28,763 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: getAttributeHandleSetFactory exception=getAttributeHandleSetFactory (909001001)

hla.rti1516e.exceptions.NotConnected: getAttributeHandleSetFactory (909001001)

at se.pitch.prti1516e.lrc.H.getAttributeHandleSetFactory(prticore_b2920:1388)

at se.pitch.prti1516e.lrc.G.getAttributeHandleSetFactory(prticore_b2920:8933)

at se.pitch.prti1516e.lrc.J.getAttributeHandleSetFactory(prticore_b2920:4616)

at de.fraunhofer.iosb.tc_lib.IVCT_RTIambassador.getAttributeHandleSetFactory(IVCT_RTIambassador.java:2243)

at de.fraunhofer.iosb.tc_lib_encodingrulestester.DataTreeBuilder.<init>(DataTreeBuilder.java:77)

at de.fraunhofer.iosb.tc_lib_encodingrulestester.EncodingRulesTesterBaseModel.processSOM(EncodingRulesTesterBaseModel.java:499)

at de.fraunhofer.iosb.tc_lib_encodingrulestester.EncodingRulesTesterBaseModel.init(EncodingRulesTesterBaseModel.java:320)

at de.fraunhofer.iosb.tc_encodingrulestester.TC0002.preambleAction(TC0002.java:103)

at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:137)

at de.fraunhofer.iosb.testrunner.TestRunner.executeTests(TestRunner.java:78)

at de.fraunhofer.iosb.testrunner.JMSTestRunner$TestScheduleRunner.run(JMSTestRunner.java:186)

at java.lang.Thread.run(Thread.java:745)

2019-04-04 14:38:28,768 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: resignFederationExecution exception=resignFederationExecution

2019-04-04 14:38:28,786 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: terminateRti: NotConnected (ignored)

2019-04-04 14:38:28,790 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: TC INCONCLUSIVE DataTreeBuilder: NotConnected

2019-04-04 14:38:28,796 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: Test Case Ended
````

**Comment by bergtwvd** [comment]
Ah, my mistake maybe. I assume RTI host and port are passed in the setting designator ?
(which this particular app does not interpret, oops).

**Comment by bergtwvd** [comment]
I'll close this for now. Needs retesting with an application that does support the local settings designator.
